# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c628c1190ee0b587949ecc7d423662c03a7d8077455abaf9b82fb82835d9ce4cb2cf63ea5f6272c58a1bee6ddf8319a3e1b05c02d11e5e467a86d3cc403b537d

test:
  secret_key_base: 01032719a7600c5ad193d38359060a789f58aa28f77eed27898c0c85dfc90c3d46dd90088a7b9a7507cfeb3977a688c10624acd258ea28505191c72e13474312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
